/** 侧栏变量。业务项目用接口数据填同样的 key。 */
export const FIELD_LABELS: Record<string, string> = {
  mark: "试打",
  donCode_Bar: "献血码条码",
  donCode_Station: "献血码站码",
  donCode_Year: "献血码年",
  donCode_NO: "献血码序号",
  donCode_State: "献血码状态",
  donCode_Check: "献血码校验",
  bloodTypeCode_Bar: "血型码条码",
  bloodTypeCode: "血型码",
  expiryCode_Bar: "有效期码条码",
  expiryCode: "有效期码",
  prodCode_Bar: "产品码条码",
  prodCode: "产品码",
  ABO: "ABO",
  RHD: "RhD",
  prodName: "产品名称",
  volumeAndUnit: "规格",
  expiryTime: "有效期至",
  collectTime: "采集时间",
  prepTime: "制备时间",
  indications: "适应证",
  precautions: "注意事项",
  solution: "保养液",
  temperature: "储存条件",
  collector: "采集者",
  preparer: "制备者",
  discardReason: "不合格项目",
};

/** 附件「合格标签传参说明」那份重庆样例。打印时原样替换。 */
export const CHONGQING_SAMPLE: Record<string, string> = {
  mark: "OK",
  donCode_Bar: "=5>500002606533455",
  donCode_Station: "50000",
  donCode_Year: "26",
  donCode_NO: "065334",
  donCode_State: "55",
  donCode_Check: "W",
  bloodTypeCode_Bar: "=%>52800",
  bloodTypeCode: "2800",
  expiryCode_Bar: "&>0>50272321357",
  expiryCode: "0272321357",
  prodCode_Bar: "=<D2140600",
  prodCode: "D2140600",
  ABO: "AB",
  RHD: "Rh(D)阳性",
  prodName: "病毒灭活新鲜冰冻血浆150ml",
  volumeAndUnit: "150 ml",
  expiryTime: "2027-08-20 13:57",
  collectTime: "2026-08-20 13:57",
  prepTime: "2027-08-20 20:08",
  indications: "临床适应症：适用于凝血因子缺乏或大量输血伴有凝血障碍",
  precautions: "注意事项：输注前请检查包装是否完好无损，外观是否正常",
  solution: "ACD-B",
  temperature: "2-6℃",
  collector: "085",
  preparer: "JSK",
};
