export const FIELD_LABELS: Record<string, string> = {
  mark: "试打",
  hospital: "医院",
  name: "姓名",
  dept: "科室",
  bed: "床号",
  visitNo: "就诊号",
  partName: "名称",
  partNo: "件号",
  serial: "序号",
  batch: "批次",
  due: "寿命至",
  title: "名称",
  sku: "物料号",
  qty: "数量",
  loc: "库位",
  note: "备注",
};

export const SAMPLE_VARS: Record<string, string> = {
  mark: "OK",
  hospital: "市第一医院",
  name: "张三",
  dept: "骨科",
  bed: "12-03",
  visitNo: "20260918001",
  partName: "液压导管",
  partNo: "A320711234",
  serial: "SN88421",
  batch: "LOT2609",
  due: "2028-03-01",
  title: "不锈钢法兰",
  sku: "A-1001",
  qty: "24",
  loc: "A-03-12",
  note: "防潮存放\\&轻拿轻放",
};
